# Generated by Django 6.0 on 2025-12-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tgprofile",
            name="tg_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
