# Generated by Django 6.0 on 2025-12-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='urgency',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='Primary', null=True),
        ),
    ]
