# Generated by Django 6.0 on 2025-12-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_category_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='urgency',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], default='Primary'),
        ),
    ]
