# Generated by Django 6.0 on 2026-02-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_category_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='urgency',
            field=models.CharField(max_length=50),
        ),
    ]
